### ISSUE TITLE
YarnManager addprocs doesn't seem to work

### ISSUE THREAD

**Issue by garybogle** [tanmaykm/Elly.jl#11]
Has anyone gotten the YarnManager to successfully addprocs()? 
I get 
julia> addprocs(yarncm, np=2, env=Dict("JULIA_PKGDIR"=>Pkg.dir()))
ERROR (unhandled task failure): Elly.YarnException("Error starting all workers. 0 of 2 started.")
 in launch at /home/gbogle/.julia/v0.4/Elly/src/cluster_manager.jl:122
 in anonymous at task.jl:63
ERROR: Elly.YarnException("Error starting all workers. 0 of 2 started.")
 in wait at ./task.jl:111
 in addprocs at multi.jl:1120

with a three node hadoop cluster with passwordless ssh working between the three machines.

**Comment by tanmaykm** [comment]
Can you see if there's any error printed in the yarn logs? That could give some clue to the failure.

The other reason could be a timeout, which is by default 60 secs. Yarn sometimes can take a while to allocate containers. You can increase the timeout by passing the `launch_timeout` optional parameter while creating `yarncm`.

**Comment by tanmaykm** [comment]
Seems to be working locally.
Please reopen if you still have issues.
