### ISSUE TITLE
Error doing readdir(): ERROR: cannot read wire type 1 as int32

### ISSUE THREAD

**Issue by garybogle** [tanmaykm/Elly.jl#13]
I get the below error when creating an HDFS client, using Cloudera Hadoop 5.5:

julia> using Elly

julia> dfs = HDFSClient("namenode", 9000)
HDFSClient: gbogle@namenode:9000/
    id: 82e850e3-43a2-48
    connected: false
    pwd: /

julia> readdir(dfs)
ERROR: cannot read wire type 1 as int32
 in error at ./error.jl:21
 in readproto at /home/gbogle/.julia/v0.4/ProtoBuf/src/codec.jl:344
 in recv_rpc_message at /home/gbogle/.julia/v0.4/Elly/src/rpc.jl:253
 in call_method at /home/gbogle/.julia/v0.4/Elly/src/rpc.jl:282
 in _walkdir at /home/gbogle/.julia/v0.4/Elly/src/api_hdfs_base.jl:138
 in readdir at /home/gbogle/.julia/v0.4/Elly/src/api_hdfs_base.jl:298
 in readdir at /home/gbogle/.julia/v0.4/Elly/src/api_hdfs_base.jl:297

**Comment by tanmaykm** [comment]
Looks like the response received from the namenode is not as expected.

Cloudera by default configures a port different than 9000 for the namenode.
Could that be the reason?

**Comment by garybogle** [comment]
Bingo! 

dfs = HDFSClient("namenode", 8020) works!

Thanks!!

**Comment by tanmaykm** [comment]
Great!
