### ISSUE TITLE
Example of reading local part of a file?

### ISSUE THREAD

**Issue by dfdx** [tanmaykm/Elly.jl#17]
Using `hdfs_blocks` we can obtain locations of data blocks, but are there any means for **reading** specific blocks from specific locations? In particular, having N Julia processes on N data nodes I'd like each process to read only its _local_ blocks. From [the code](https://github.com/JuliaParallel/Elly.jl/blob/master/src/api_hdfs_io.jl) it seems to be easy to implement, but maybe there's already and API for this?

And a related question: are there any predefined readers/formatters? For example, if we work with a text file, then most probably the end of a line will not match the end of a block, so a client should read a little piece of data from another location. In Java, [TextInputFormat](https://hadoop.apache.org/docs/r2.4.1/api/org/apache/hadoop/mapreduce/lib/input/TextInputFormat.html) handles it automatically. Do we have anything similar for Julia?

**Comment by tanmaykm** [comment]
A separate package https://github.com/tanmaykm/HadoopBlocks.jl has the beginnings of some of those

**Comment by dfdx** [comment]
Ok, I need some time to get into it, but it's mostly unrelated to this issue. Closing it.  
Thanks!
