### ISSUE TITLE
Yarn ClusterManager tutorial

### ISSUE THREAD

**Issue by jpfairbanks** [tanmaykm/Elly.jl#27]
I am working through the Yarn ClusterManager tutorial https://github.com/JuliaParallel/Elly.jl/blob/master/YARNCM.md and noticed that there are no instructions for finding out the connection info for the yarn cluster. Is this info found in $HADOOP_CONF_DIR/yarn-site.xml?

**Comment by tanmaykm** [comment]
Yes that's usually where it is found. There could be different ways to find the connection information, depending on the Hadoop distribution and the environment. I agree that it would be good to mention this for a few known distributions.

Will gladly accept a pull request for the doc changes!

**Comment by jpfairbanks** [comment]
Is there some authoritative source on finding this that I could cite? I looked through the output of  `env` for the HADOOP path variables that my sysadmin set (using `module load hadoop`) and searched through the files in that directory until I saw the right variables.

**Comment by tanmaykm** [comment]
Here's one link for the Apache distribution: https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/ClusterSetup.html

It mentions the parameters to look for in `$HADOOP_CONF_DIR/yarn-site.xml`.
