### ISSUE TITLE
Is it possible to get block locations of HDFS?

### ISSUE THREAD

**Issue by dfdx** [tanmaykm/Elly.jl#3]
Java API provides methods for obtaining file block locations (e.g. see [`FileSystem.getFileBlockLocations`](https://hadoop.apache.org/docs/current/api/org/apache/hadoop/fs/FileSystem.html#getFileBlockLocations%28org.apache.hadoop.fs.Path, long, long%29)). This method is essential for making computations to be _local_ to data. Does Elly.jl expose this functionality?

**Comment by tanmaykm** [comment]
Yes, the `hdfs_blocks` method should give that.

Unfortunately, not all exported methods (from https://github.com/JuliaParallel/Elly.jl/blob/master/src/Elly.jl) have been documented yet.

**Comment by dfdx** [comment]
This is great, thank you!
