### ISSUE TITLE
Installs troubles

### ISSUE THREAD

**Issue by quasiben** [tanmaykm/Elly.jl#4]
i'm fairly new to Julia -- please forgive any ignorance here.  I'm trying to install Elly and I'm getting some errors:

```
julia> Pkg.add("Elly")
ERROR: Elly's requirements can't be satisfied because of the following fixed packages: julia
 in error at error.jl:22
 in resolve at pkg/entry.jl:321
 in resolve at pkg/entry.jl:316
 in edit at pkg/entry.jl:24
 in add at pkg/entry.jl:44
 in add at pkg/entry.jl:48
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:22
 in cd at pkg/dir.jl:28
 in add at pkg.jl:19
```

Running on Ubuntu 12.04 and installing Julia from apt

**Comment by tanmaykm** [comment]
I don't think using `apt` on Ubuntu 12.04 would get you the version of Julia required for Elly (v0.4).

Could you try this on Julia v0.4 installed using of the methods listed here: http://julialang.org/downloads/ ?

**Comment by quasiben** [comment]
Apologies for the delay.  Upgrading to 0.4 worked for me!
