### ISSUE TITLE
Understanding Tokens

### ISSUE THREAD

**Issue by quasiben** [tanmaykm/Elly.jl#5]
Any chance we could chat briefly about adding tokens using the protobuf interface.  Not sure I totally understand what's happening with `add_token` here or with the [go interface](https://github.com/hortonworks/gohadoop)

**Comment by tanmaykm** [comment]
Security delegation tokens are structures of type [TokenProto](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/hadoop/Security_pb.jl#L6). Basically, credentials for a service of a certain kind.

Tokens are used to authenticate requests [here](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/sasl.jl#L95) or [read from HDFS](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/rpc.jl#L918).

The Yarn application master may get tokens from the resource manager during its interactions (e.g. [here](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/api_yarn_appmaster.jl#L87) and [here](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/api_yarn_appmaster.jl#L228). The tokens may be meant for yarn node managers or the yarn resource manager itself.

The Yarn application master stores all tokens in the [UGI structure](https://github.com/JuliaParallel/Elly.jl/blob/795849c8a8d7af395052ec91ccf1f9fa9fa33204/src/ugi.jl#L13).

**Comment by tanmaykm** [comment]
Hi @quasiben. Did this help explain the token mechanism?

**Comment by quasiben** [comment]
@tanmaykm, yes thank you!  One lingering thought is around the `UGI`.  UGI + Token isn't _really_ built into the Protobuf interface.  Is that right?  My current understanding is that the `UserInformationProto` holds onto metadata about the user but not auth/tokens.  

Thank you for taking the time to answer these tangential YARN/Protobuf questions

**Comment by tanmaykm** [comment]
@quasiben Yes, that's true. In fact, `UGI = UserInformationProto + Tokens`, and that's specific to the implementation here.

**Comment by quasiben** [comment]
Thank you again!
